# Generated by Django 4.0.2 on 2022-02-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFQReceived',
            fields=[
                ('idNumber', models.BigAutoField(primary_key=True, serialize=False)),
                ('partNumber', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('quantityRequired', models.IntegerField()),
                ('UOM', models.TextField()),
                ('leadTime', models.DateField()),
                ('remarks', models.TextField()),
            ],
        ),
    ]
