# Generated by Django 4.0.2 on 2022-02-09 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientQuatation',
            fields=[
                ('quoteNumber', models.BigAutoField(primary_key=True, serialize=False)),
                ('partNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPanel.rfqreceived')),
            ],
        ),
    ]
