# Generated by Django 4.0.2 on 2022-02-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_clientquatation'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientquatation',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rfqreceived',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
