# Generated by Django 4.0.2 on 2022-02-09 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0003_clientquatation_isactive_rfqreceived_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientquatation',
            name='Currency',
            field=models.CharField(choices=[('RS', 'Rupees'), ('USD', 'US Dollars'), ('AUD', 'Australian Dollars')], default='RS', max_length=10),
        ),
        migrations.AddField(
            model_name='clientquatation',
            name='INCOTERMS',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clientquatation',
            name='MOQ',
            field=models.IntegerField(default=0, help_text='Minimum order to be placed'),
        ),
        migrations.AddField(
            model_name='clientquatation',
            name='PriceInclusiveTaxes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientquatation',
            name='SPQ',
            field=models.IntegerField(default=0, help_text='Factory packed quantity'),
        ),
        migrations.AddField(
            model_name='clientquatation',
            name='UOM',
            field=models.CharField(default='Nos', help_text='Units of Measurement', max_length=20),
        ),
        migrations.AddField(
            model_name='clientquatation',
            name='UnitPrice',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientquatation',
            name='description',
            field=models.TextField(default='NotPossible'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientquatation',
            name='manufacturer',
            field=models.CharField(default='Amdocs', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfqreceived',
            name='AlternatePartNumber',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rfqreceived',
            name='ClosureOfRFQ',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rfqreceived',
            name='DateOfRFQ',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfqreceived',
            name='OfficerName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rfqreceived',
            name='RFQNotes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rfqreceived',
            name='RFQNumber',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='rfqreceived',
            name='TargetPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rfqreceived',
            name='UOM',
            field=models.CharField(default='Nos', help_text='Units of Measurement', max_length=20),
        ),
        migrations.AlterField(
            model_name='rfqreceived',
            name='manufacturer',
            field=models.CharField(max_length=30),
        ),
    ]
